/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRequestsRouteImport } from './routes/_protected/requests'
import { Route as ProtectedMarketplaceRouteImport } from './routes/_protected/marketplace'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as ProtectedRequestsOutgoingRouteImport } from './routes/_protected/requests/outgoing'
import { Route as ProtectedRequestsIncomingRouteImport } from './routes/_protected/requests/incoming'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRequestsRoute = ProtectedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMarketplaceRoute = ProtectedMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRequestsOutgoingRoute =
  ProtectedRequestsOutgoingRouteImport.update({
    id: '/outgoing',
    path: '/outgoing',
    getParentRoute: () => ProtectedRequestsRoute,
  } as any)
const ProtectedRequestsIncomingRoute =
  ProtectedRequestsIncomingRouteImport.update({
    id: '/incoming',
    path: '/incoming',
    getParentRoute: () => ProtectedRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/marketplace': typeof ProtectedMarketplaceRoute
  '/requests': typeof ProtectedRequestsRouteWithChildren
  '/requests/incoming': typeof ProtectedRequestsIncomingRoute
  '/requests/outgoing': typeof ProtectedRequestsOutgoingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/marketplace': typeof ProtectedMarketplaceRoute
  '/requests': typeof ProtectedRequestsRouteWithChildren
  '/requests/incoming': typeof ProtectedRequestsIncomingRoute
  '/requests/outgoing': typeof ProtectedRequestsOutgoingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/marketplace': typeof ProtectedMarketplaceRoute
  '/_protected/requests': typeof ProtectedRequestsRouteWithChildren
  '/_protected/requests/incoming': typeof ProtectedRequestsIncomingRoute
  '/_protected/requests/outgoing': typeof ProtectedRequestsOutgoingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/marketplace'
    | '/requests'
    | '/requests/incoming'
    | '/requests/outgoing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/marketplace'
    | '/requests'
    | '/requests/incoming'
    | '/requests/outgoing'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(public)/login'
    | '/(public)/register'
    | '/_protected/dashboard'
    | '/_protected/marketplace'
    | '/_protected/requests'
    | '/_protected/requests/incoming'
    | '/_protected/requests/outgoing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/requests': {
      id: '/_protected/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof ProtectedRequestsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/marketplace': {
      id: '/_protected/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof ProtectedMarketplaceRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/requests/outgoing': {
      id: '/_protected/requests/outgoing'
      path: '/outgoing'
      fullPath: '/requests/outgoing'
      preLoaderRoute: typeof ProtectedRequestsOutgoingRouteImport
      parentRoute: typeof ProtectedRequestsRoute
    }
    '/_protected/requests/incoming': {
      id: '/_protected/requests/incoming'
      path: '/incoming'
      fullPath: '/requests/incoming'
      preLoaderRoute: typeof ProtectedRequestsIncomingRouteImport
      parentRoute: typeof ProtectedRequestsRoute
    }
  }
}

interface ProtectedRequestsRouteChildren {
  ProtectedRequestsIncomingRoute: typeof ProtectedRequestsIncomingRoute
  ProtectedRequestsOutgoingRoute: typeof ProtectedRequestsOutgoingRoute
}

const ProtectedRequestsRouteChildren: ProtectedRequestsRouteChildren = {
  ProtectedRequestsIncomingRoute: ProtectedRequestsIncomingRoute,
  ProtectedRequestsOutgoingRoute: ProtectedRequestsOutgoingRoute,
}

const ProtectedRequestsRouteWithChildren =
  ProtectedRequestsRoute._addFileChildren(ProtectedRequestsRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMarketplaceRoute: typeof ProtectedMarketplaceRoute
  ProtectedRequestsRoute: typeof ProtectedRequestsRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMarketplaceRoute: ProtectedMarketplaceRoute,
  ProtectedRequestsRoute: ProtectedRequestsRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
