/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRequestsRouteImport } from './routes/_protected/requests'
import { Route as ProtectedMarketplaceRouteImport } from './routes/_protected/marketplace'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRequestsRoute = ProtectedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMarketplaceRoute = ProtectedMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/marketplace': typeof ProtectedMarketplaceRoute
  '/requests': typeof ProtectedRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/marketplace': typeof ProtectedMarketplaceRoute
  '/requests': typeof ProtectedRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/marketplace': typeof ProtectedMarketplaceRoute
  '/_protected/requests': typeof ProtectedRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/marketplace'
    | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/dashboard' | '/marketplace' | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(public)/login'
    | '/(public)/register'
    | '/_protected/dashboard'
    | '/_protected/marketplace'
    | '/_protected/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/requests': {
      id: '/_protected/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof ProtectedRequestsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/marketplace': {
      id: '/_protected/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof ProtectedMarketplaceRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMarketplaceRoute: typeof ProtectedMarketplaceRoute
  ProtectedRequestsRoute: typeof ProtectedRequestsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMarketplaceRoute: ProtectedMarketplaceRoute,
  ProtectedRequestsRoute: ProtectedRequestsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
