// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Event struct {
	ID        int64
	Title     string
	StartTime time.Time
	EndTime   time.Time
	Status    string
	UserID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SwapRequest struct {
	ID              int64
	RequesterUserID int64
	ResponderUserID int64
	RequesterSlotID int64
	ResponderSlotID int64
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
