// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title,
    start_time,
    end_time,
    status,
    user_id
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, title, start_time, end_time, status, user_id, created_at, updated_at
`

type CreateEventParams struct {
	Title     string    `json:"title"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Status    string    `json:"status"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSwapRequest = `-- name: CreateSwapRequest :one
INSERT INTO swap_requests (
    requester_user_id,
    responder_user_id,
    requester_slot_id,
    responder_slot_id,
    status
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, requester_user_id, responder_user_id, requester_slot_id, responder_slot_id, status, created_at, updated_at
`

type CreateSwapRequestParams struct {
	RequesterUserID int64  `json:"requester_user_id"`
	ResponderUserID int64  `json:"responder_user_id"`
	RequesterSlotID int64  `json:"requester_slot_id"`
	ResponderSlotID int64  `json:"responder_slot_id"`
	Status          string `json:"status"`
}

func (q *Queries) CreateSwapRequest(ctx context.Context, arg CreateSwapRequestParams) (SwapRequest, error) {
	row := q.db.QueryRowContext(ctx, createSwapRequest,
		arg.RequesterUserID,
		arg.ResponderUserID,
		arg.RequesterSlotID,
		arg.ResponderSlotID,
		arg.Status,
	)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.ResponderUserID,
		&i.RequesterSlotID,
		&i.ResponderSlotID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password
) VALUES (
    ?,
    ?,
    ?
) RETURNING id, name, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = ?
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteSwapRequest = `-- name: DeleteSwapRequest :exec
DELETE FROM swap_requests
WHERE id = ?
`

func (q *Queries) DeleteSwapRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSwapRequest, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, start_time, end_time, status, user_id, created_at, updated_at FROM events
WHERE id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventsByUserID = `-- name: GetEventsByUserID :many
SELECT id, title, start_time, end_time, status, user_id, created_at, updated_at FROM events
WHERE user_id = ?
`

func (q *Queries) GetEventsByUserID(ctx context.Context, userID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByUserIDAndStatus = `-- name: GetEventsByUserIDAndStatus :many
SELECT id, title, start_time, end_time, status, user_id, created_at, updated_at FROM events
WHERE user_id = ? AND status = ?
`

type GetEventsByUserIDAndStatusParams struct {
	UserID int64  `json:"user_id"`
	Status string `json:"status"`
}

func (q *Queries) GetEventsByUserIDAndStatus(ctx context.Context, arg GetEventsByUserIDAndStatusParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByUserIDAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingSwapRequests = `-- name: GetIncomingSwapRequests :many
SELECT
    sr.id,
    sr.status,
    sr.requester_user_id,
    requester.name AS requester_name,
    requester_event.title AS requester_event_title,
    requester_event.start_time AS requester_event_start_time,
    requester_event.end_time AS requester_event_end_time,
    responder_event.title AS responder_event_title,
    responder_event.start_time AS responder_event_start_time,
    responder_event.end_time AS responder_event_end_time
FROM
    swap_requests sr
JOIN
    users requester ON sr.requester_user_id = requester.id
JOIN
    events requester_event ON sr.requester_slot_id = requester_event.id
JOIN
    events responder_event ON sr.responder_slot_id = responder_event.id
WHERE
    sr.responder_user_id = ? AND sr.status = 'PENDING'
`

type GetIncomingSwapRequestsRow struct {
	ID                      int64     `json:"id"`
	Status                  string    `json:"status"`
	RequesterUserID         int64     `json:"requester_user_id"`
	RequesterName           string    `json:"requester_name"`
	RequesterEventTitle     string    `json:"requester_event_title"`
	RequesterEventStartTime time.Time `json:"requester_event_start_time"`
	RequesterEventEndTime   time.Time `json:"requester_event_end_time"`
	ResponderEventTitle     string    `json:"responder_event_title"`
	ResponderEventStartTime time.Time `json:"responder_event_start_time"`
	ResponderEventEndTime   time.Time `json:"responder_event_end_time"`
}

func (q *Queries) GetIncomingSwapRequests(ctx context.Context, responderUserID int64) ([]GetIncomingSwapRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncomingSwapRequests, responderUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncomingSwapRequestsRow
	for rows.Next() {
		var i GetIncomingSwapRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.RequesterUserID,
			&i.RequesterName,
			&i.RequesterEventTitle,
			&i.RequesterEventStartTime,
			&i.RequesterEventEndTime,
			&i.ResponderEventTitle,
			&i.ResponderEventStartTime,
			&i.ResponderEventEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingSwapRequests = `-- name: GetOutgoingSwapRequests :many
SELECT
    sr.id,
    sr.status,
    sr.responder_user_id,
    responder.name AS responder_name,
    requester_event.title AS requester_event_title,
    requester_event.start_time AS requester_event_start_time,
    requester_event.end_time AS requester_event_end_time,
    responder_event.title AS responder_event_title,
    responder_event.start_time AS responder_event_start_time,
    responder_event.end_time AS responder_event_end_time
FROM
    swap_requests sr
JOIN
    users responder ON sr.responder_user_id = responder.id
JOIN
    events requester_event ON sr.requester_slot_id = requester_event.id
JOIN
    events responder_event ON sr.responder_slot_id = responder_event.id
WHERE
    sr.requester_user_id = ? AND sr.status = 'PENDING'
`

type GetOutgoingSwapRequestsRow struct {
	ID                      int64     `json:"id"`
	Status                  string    `json:"status"`
	ResponderUserID         int64     `json:"responder_user_id"`
	ResponderName           string    `json:"responder_name"`
	RequesterEventTitle     string    `json:"requester_event_title"`
	RequesterEventStartTime time.Time `json:"requester_event_start_time"`
	RequesterEventEndTime   time.Time `json:"requester_event_end_time"`
	ResponderEventTitle     string    `json:"responder_event_title"`
	ResponderEventStartTime time.Time `json:"responder_event_start_time"`
	ResponderEventEndTime   time.Time `json:"responder_event_end_time"`
}

func (q *Queries) GetOutgoingSwapRequests(ctx context.Context, requesterUserID int64) ([]GetOutgoingSwapRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutgoingSwapRequests, requesterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutgoingSwapRequestsRow
	for rows.Next() {
		var i GetOutgoingSwapRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ResponderUserID,
			&i.ResponderName,
			&i.RequesterEventTitle,
			&i.RequesterEventStartTime,
			&i.RequesterEventEndTime,
			&i.ResponderEventTitle,
			&i.ResponderEventStartTime,
			&i.ResponderEventEndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicUserByID = `-- name: GetPublicUserByID :one
SELECT id, name, created_at, updated_at FROM users
WHERE id = ?
`

type GetPublicUserByIDRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetPublicUserByID(ctx context.Context, id int64) (GetPublicUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicUserByID, id)
	var i GetPublicUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSwapRequestByID = `-- name: GetSwapRequestByID :one
SELECT id, requester_user_id, responder_user_id, requester_slot_id, responder_slot_id, status, created_at, updated_at FROM swap_requests
WHERE id = ?
`

func (q *Queries) GetSwapRequestByID(ctx context.Context, id int64) (SwapRequest, error) {
	row := q.db.QueryRowContext(ctx, getSwapRequestByID, id)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.ResponderUserID,
		&i.RequesterSlotID,
		&i.ResponderSlotID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSwapRequestsByEventID = `-- name: GetSwapRequestsByEventID :many
SELECT id, requester_user_id, responder_user_id, requester_slot_id, responder_slot_id, status, created_at, updated_at FROM swap_requests
WHERE requester_slot_id = ? OR responder_slot_id = ?
`

type GetSwapRequestsByEventIDParams struct {
	RequesterSlotID int64 `json:"requester_slot_id"`
	ResponderSlotID int64 `json:"responder_slot_id"`
}

func (q *Queries) GetSwapRequestsByEventID(ctx context.Context, arg GetSwapRequestsByEventIDParams) ([]SwapRequest, error) {
	rows, err := q.db.QueryContext(ctx, getSwapRequestsByEventID, arg.RequesterSlotID, arg.ResponderSlotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SwapRequest
	for rows.Next() {
		var i SwapRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserID,
			&i.ResponderUserID,
			&i.RequesterSlotID,
			&i.ResponderSlotID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSwappableEvents = `-- name: GetSwappableEvents :many
SELECT
    e.id, e.title, e.start_time, e.end_time, e.status, e.user_id, e.created_at, e.updated_at,
    u.name as owner_name
FROM events e
JOIN users u ON e.user_id = u.id
WHERE e.status = 'SWAPPABLE' AND e.user_id != ?
`

type GetSwappableEventsRow struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Status    string    `json:"status"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	OwnerName string    `json:"owner_name"`
}

func (q *Queries) GetSwappableEvents(ctx context.Context, userID int64) ([]GetSwappableEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSwappableEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSwappableEventsRow
	for rows.Next() {
		var i GetSwappableEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, created_at, updated_at FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, created_at, updated_at FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = ?,
    start_time = ?,
    end_time = ?,
    status = ?
WHERE id = ?
RETURNING id, title, start_time, end_time, status, user_id, created_at, updated_at
`

type UpdateEventParams struct {
	Title     string    `json:"title"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Status    string    `json:"status"`
	ID        int64     `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventStatus = `-- name: UpdateEventStatus :one
UPDATE events
SET status = ?
WHERE id = ?
RETURNING id, title, start_time, end_time, status, user_id, created_at, updated_at
`

type UpdateEventStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEventStatus, arg.Status, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventUserID = `-- name: UpdateEventUserID :one
UPDATE events
SET user_id = ?
WHERE id = ?
RETURNING id, title, start_time, end_time, status, user_id, created_at, updated_at
`

type UpdateEventUserIDParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateEventUserID(ctx context.Context, arg UpdateEventUserIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEventUserID, arg.UserID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSwapRequestStatus = `-- name: UpdateSwapRequestStatus :one
UPDATE swap_requests
SET status = ?
WHERE id = ?
RETURNING id, requester_user_id, responder_user_id, requester_slot_id, responder_slot_id, status, created_at, updated_at
`

type UpdateSwapRequestStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateSwapRequestStatus(ctx context.Context, arg UpdateSwapRequestStatusParams) (SwapRequest, error) {
	row := q.db.QueryRowContext(ctx, updateSwapRequestStatus, arg.Status, arg.ID)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserID,
		&i.ResponderUserID,
		&i.RequesterSlotID,
		&i.ResponderSlotID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
